server:
  port: 8084
spring:
  redis:
    host: localhost
    port: 6379
    connection:
      timeout: 10000
  kafka:
    consumer:
      bootstrap-servers: localhost:9091
      topics: Post,Following
      group-id: feedServiceGroup
      auto-offset-reset: earliest

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration